name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend dependencies
        run: |
          cd kinology_frontend
          npm install

      - name: Install backend dependencies
        run: |
          cd kinology_backend
          npm install

      - name: Frontend unit tests
        run: |
          cd kinology_frontend
          npm test

      - name: Build
        run: |
          cd kinology_backend
          npm run build:ui

      - name: Run backend integration tests
        env:
          NODE_ENV: test
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          cd kinology_backend
          npm test -- ./tests/comments_api.test.js && 
          npm test -- ./tests/login_api.test.js && 
          npm test -- ./tests/movies_api.test.js && 
          npm test -- ./tests/users_api.test.js
