name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend dependencies
        run: |
          cd kinology_frontend
          npm install

      - name: Install backend dependencies
        run: |
          cd kinology_backend
          npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 7.0.0

      - name: Frontend unit tests
        run: |
          cd kinology_frontend
          npm test

      - name: Build
        run: npm run build:ui

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install-deps chromium
      - name: e2e tests
        run: npm run test:e2e
